### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by arnavaz** [morrislab/phylowgs#1]
Hi!

It is not really clear what the format of the input data is. Could you please give some more information on how to create the input files?
Thanks
Arna

**Comment by jwintersinger** [comment]
Hi Arnavaz,

(I'm listing my response to your e-mail here so that others may benefit from it.)

Providing CNVs can be tricky, as PhyloWGS treats CNVs similar to SNVs.  Consequently, some of the fields required aren't intuitive. Let me give you an example.

* Suppose you have a CNV you observed in 56% of cells in your sample. 
* Then, your "variant allele frequency" will be 0.28, since the number of chromosomes containing this CNV should be half the number of cells.
* Set d to an arbitrarily large number, representing the number of reference "reads" that covered this locus. d = 100,000 should work.  Set a = (1 - VAF) * d = (1 - 0.28) * 100,000 = 72,000.
* For "ssms", specify the list of SNVs overlapping this SNV as specified in the README.

I hope this helps!

**Comment by bioinflix** [comment]
Hi,

I try to run PhyloWGS with my data which following the input file format, but only crushed the error report:

Traceback (most recent call last):
  File "/Software/phylowgs-master/evolve.py", line 231, in <module>
    rand_seed=args.random_seed
  File "/Software/phylowgs-master/evolve.py", line 56, in run
    codes, n_ssms, n_cnvs = load_data(fin1,fin2)
  File "/Software/phylowgs-master/util2.py", line 39, in load_data
    d = [int(x) for x in row['d'].split(',')]
ValueError: invalid literal for int() with base 10: '0.999'

Any suggestion for this?
Thanks!

Lisa

**Comment by svembu** [comment]
Lisa, you may want to check your input data format. It looks like you have 0.999 in the column where integer counts (d) are expected. Please check the sample data files for the correct format.

**Comment by bioinflix** [comment]
Sorry, I checked my input and it actually turned out it's my wrong format. 
However, there is one new error after I use the right input file format:

Starting MCMC run...
-1000
Traceback (most recent call last):
  File "/Software/phylowgs-master/evolve.py", line 231, in <module>
    rand_seed=args.random_seed
  File "/Software/phylowgs-master/evolve.py", line 120, in run
    mh_acc = metropolis(tssb,mh_itr,mh_std,mh_burnin,n_ssms,n_cnvs,fin1,fin2,rand_seed,NTPS)
  File "/Software/phylowgs-master/params.py", line 54, in metropolis
    ar = str(loadtxt(FNAME_C_MH_ARATIO,dtype='string'))
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 734, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'c_mh_ar_S1_SSM_forPhyloWGS_1.txt'

There only generated two files: c_data_states_S1_SSM_forPhyloWGS_1.txt; c_tree_S1_SSM_forPhyloWGS_1.txt, and there is no files under the directory "trees".

Can anyone help to fix this?

BTW, what is the format for the output file? I'm sorry I didn't see any column names in the output file or there seems no other description for the output file format.

**Comment by svembu** [comment]
Would you be able to send the data files to us, so that we can try to reproduce the error on our side?

**Comment by svembu** [comment]
Would you be able to send the data files to us, so that we can try to reproduce the error on our side?

**Comment by bioinflix** [comment]
svembu, can you offer me your e-mail?
Thanks a lot!
