### ISSUE TITLE
CNV input for running phyloWGS on multiple samples

### ISSUE THREAD

**Issue by yjiao** [morrislab/phylowgs#25]
Hello,

I have longitudinal tumor samples that I am trying to use phyloWGS on. I have managed to generate ssm_data.txt based on the example. However, I'm not sure how to create cnv_data.txt for multiple samples, since each sample has its own unique segment break points. Do I need to force all the segments to have the same break points? Is this an option in the provided parser?

Thanks a lot!

**Comment by jwintersinger** [comment]
Hi @yjiao,

At the moment, the parser does not support multi-sample SSMs or CNVs. We will soon be updating the parser to supprot multi-sample SSMs, but we haven't thought extensively about how we wish to handle multi-sample CNVs.

In [cnv_data.txt](https://github.com/morrislab/phylowgs/blob/master/cnv_data.txt), you can see that CNVs are treated as pseudo-SSMs by the model -- they have `a` and `d` values, with `a / d` roughly indicating the proportion of total chromosomes sequenced affected by the CNV, and the magnitude of `a` and `d` indicating how certain you are in this CNV. Factors such as a larger CNV (in terms of number of bases spanned) or higher read depth will result in `a` and `d` values of higher magnitude because they increase certainty.

Consequently, the parser only uses breakpoints to determine the certainty of the CNV. How did you do your CNV calling? Is it possible to force them to have the same breakpoints?

**Comment by yjiao** [comment]
Hi @jwintersinger,

Thanks for the quick reply! 

It makes sense that the breakpoints would be the unique identifiers for CNVs. I'm using ABSOLUTE to call the CNVs. The samples are called individually so they tend to have many different breakpoints. To force them to have the same breakpoints, I can generate a list of breakpoints from the set of all samples of a patient, and then go through each segment in each sample and break them into smaller chunks to match this list.

However, there are some scenarios that I am not sure how to deal with. For example, if a locus gains a SSM, and then undergoes duplication, some samples will have 1 copy of the SSM, and others will have 2 copies of the SSM. cnv_data.txt explicitly states the copy numbers of each SSM. In this case, should I create 2 SSMS s0 and s1, with all fields equal except for copy numbers?

Thanks a lot!

**Comment by hxrts** [comment]
Bumping this question. @jwintersinger appreciate any guidance you can offer as to how we should treat this case.

**Comment by jwintersinger** [comment]
Hi,
We would love to be able to support these cases. Unfortunately we don't have the resources or time to do this yet. It's on the TODO list though, thanks for bringing it up.
