### ISSUE TITLE
Question: correcting for tumor purity?

### ISSUE THREAD

**Issue by selinj** [morrislab/phylowgs#26]
Hi! Do you have a standard practice for correcting SSM read counts for tumor purity? I notice there's an option for cellularity in the CNV pre-parser but not the primary parser?

Thanks.

**Comment by jwintersinger** [comment]
We don't correct SSM read counts for tumor purity, just put in the actual counts. Phylo* will estimate purity for you. Witness reports both cellular prevalence and CCF.

The CNV pre-parser takes cellularity as an argument in order to identify the clonal CNAs so that we can merge them together. It does not correct for purity either.
