### ISSUE TITLE
top_k_trees don't match tree viewer?

### ISSUE THREAD

**Issue by yjiao** [morrislab/phylowgs#29]
Hello,

It looks like none of the trees saved in "top_k_trees" actually match those from the PhyloWGS Witness
tree viewer. For example, all the trees in "top_k_trees" has 11 nodes (0-10), and the max number of nodes found in Witness is just 10 (0-9). 

I'm a bit confused about which file I should "believe" if I just want to grab the information for the most likely tree? Any guidance on how to parse the final results would be greatly appreciated.

Thanks!

**Comment by jwintersinger** [comment]
Hi,
I suspect that the difference is because Witness removes nodes with <1% cellular prevalence. Can you quickly check whether that is the cause of the difference? That said, please use Witness instead of top_k_trees which is deprecated.

Also note that you can sort by likelihood (LLH) in Witness, those trees with the highest LLH should match the ones in top_k_trees.
