### ISSUE TITLE
cnvs in CN normal regions

### ISSUE THREAD

**Issue by callosciurus** [morrislab/phylowgs#32]
I noticed that CNVs in CN normal regions are not being written to file, even when --only-normal-cn is not passed to the parser.

There is a line in write_cnvs that filters out all regions that are not CN-normal, before they're written to file:
abnormal_regions[chrom] = [r for r in regions if not self._is_region_normal_cn(r)]

write_cnvs is called from here:

 if not args.only_normal_cn and grouper.has_cnvs():
    grouper.write_cnvs(subsampled_vars, args.output_cnvs, args.cnv_confidence, args.read_length)

Are these regions filtered out intentionally? According to the documentation "You do not specify --only-normal-cn: All variants falling in regions listed in cnvs.txt will be output.", but that doesn't seem to happen here.

**Comment by quaidmorris** [comment]
Hi @callosciurus,

Thank-you very much for your feedback and your effort to bug track.

Would you mind expanding on your question a bit, because I'm not sure I understand it. Specifically, why would you expect a CNA to fall into a CN normal region? In the documentation, the term "variant" refers to SSMs not CNAs; we should edit that if it's confusing.

[I'm using copy number aberration (CNA) instead of CNV for clarity]

**Comment by callosciurus** [comment]
Sure. I was just trying to understand why certain CNVs and variants were
filtered out by the parser. I'll post an example in a bit. Thanks!

**Comment by callosciurus** [comment]
@quaidmorris see example below. I noticed that 1) not all mutations from the input file are written to the ssm_data.txt output file. I was trying to figure out why that is the case. So then I saw that 2) only non-diploid regions are found in cnv_data.txt.

I understand that CNA are not found in diploid regions by definition. But according to the documentation ('You do not specify --only-normal-cn: All variants falling in regions listed in cnvs.txt will be output.'), I was expecting even diploid regions in the cnv_data.txt output files. 

I am actually not so worried about diploid regions, but more interested to understand the first issue, i.e. why some mutations are filtered out. I thought that 1) was related to 2), but I realize that is probably not the case?


**input vcf**
##fileformat=VCFv4.1
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP Membership">
##FORMAT=<ID=TD,Number=.,Type=Integer,Description="Tumor allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=ND,Number=.,Type=Integer,Description="Normal allelic depths for the ref and alt alleles in the order listed">
##INFO=<ID=TR,Number=1,Type=Integer,Description="Approximate tumor read depth; some reads may have been filtered">
##INFO=<ID=NR,Number=1,Type=Integer,Description="Approximate normal read depth; some reads may have been filtered">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLENAME
1       26608867        .       C       A       30.0    .       SOMATIC TD:ND:TR:NR     10,8:10,0:18:10
9       76800014        .       A       G       30.0    .       SOMATIC TD:ND:TR:NR     41,8:21,0:49:21
11      18331921        .       G       A       30.0    .       SOMATIC TD:ND:TR:NR     13,4:9,0:17:9
11      22817278        .       T       A       30.0    .       SOMATIC TD:ND:TR:NR     57,8:24,0:65:24
11      50139111        .       T       G       30.0    .       SOMATIC TD:ND:TR:NR     41,8:13,0:49:13
16      49850505        .       C       T       30.0    .       SOMATIC TD:ND:TR:NR     75,5:44,0:80:44
16      195510446       .       C       G       30.0    .       SOMATIC TD:ND:TR:NR     31,6:20,0:37:20
16      197880129       .       T       C       30.0    .       SOMATIC TD:ND:TR:NR     219,10:109,0:229:109
17      190989759       .       G       A       30.0    .       SOMATIC TD:ND:TR:NR     36,7:11,0:43:11
17      190989760       .       C       G       30.0    .       SOMATIC TD:ND:TR:NR     36,7:12,0:43:12

**input CN file**
chromosome      start   end     copy_number     minor_cn        major_cn        cellular_prevalence
1       13273   249212429       2       1       1       1
2       41620   243064404       2       1       1       1
3       239500  197896818       2       1       1       1
4       53360   191030100       2       1       1       1
5       140722  180710506       2       1       1       1
6       203397  171037558       2       1       1       1
7       19691   159026034       2       1       1       1
8       116699  146279514       2       1       1       1
9       12920   136321653       2       1       1       1
9       136322000       140332456       3       1       2       0.189485812985688
10      93046   135491077       2       1       1       1
11      134550  134856497       2       1       1       1
12      67849   133810949       2       1       1       1
13      19043328        115091663       2       1       1       1
14      19110349        107283296       2       1       1       1
15      20084088        102517820       2       1       1       1
16      61858   2337993 2       1       1       1
16      2338363 81679339        2       1       1       1
16      81685954        90238127        2       1       1       1
17      6073    81050998        2       1       1       1
18      47492   78005093        2       1       1       1
19      107632  59096116        2       1       1       1
20      68474   62959306        2       1       1       1
21      9590334 48084202        2       1       1       1
22      16123182        51237486        2       1       1       1

**ssm_data.txt**
id      gene    a       d       mu_r    mu_v
s0      1_26608867      10      18      0.999   0.499
s1      9_76800014      41      49      0.999   0.499
s2      11_18331921     13      17      0.999   0.499
s3      11_22817278     57      65      0.999   0.499
s4      11_50139111     41      49      0.999   0.499
s5      16_49850505     75      80      0.999   0.499

**cnv_data.txt**
cnv     a       d       ssms
c0      89595   98972

**Comment by jwintersinger** [comment]
Hi @callosciurus,

What you're seeing is the expected behaviour. There is a distinction between `cnvs.txt` and `cnv_data.txt`, which is, admittedly, confusing.

* `cnvs.txt` uses a tool-neutral format for listing CNAs that we defined, analogous to the purpose VCF serves for SNVs. It is used by the parser, but not PhyloWGS itself. The parser uses this data to produce `cnv_data.txt`. Variants falling outside regions in `cnvs.txt` are always ignored, as we take this to mean that the CNA caller had no idea what the copy number status of the region in question was.

* `cnv_data.txt` is directly used by PhyloWGS to place CNAs on the phylogenies it produces. This file doesn't explicitly list things such as the start position, end position, or cellular prevalence of CNAs; it only provides enough information for PhyloWGS to cluster the CNA. Normal-CN regions are not placed on the phylogenies, and so they're not included in this file.

Thus:

* If `--only-normal-cn` is specified: variants in non-normal regions will be ignored. `cnv_data.txt` will be empty, as this option indicates you don't want to place CNAs on the phylogenies.

* If `--only-normal-cn` isn't specified: variants in CN-aberrant regions *will* be included. `cnv_data.txt` will contain CNAs corresponding to the CN-aberrant regions specified in `cnvs.txt`.

Does this make sense?

**Comment by callosciurus** [comment]
@jwintersinger yes that makes sense now.

What about the mutations that are being filtered out? There are 10 variant in the vcf input file, but only 6 in the ssm_data.txt. This is just a small example, but even in the number of mutations is much larger, I see ~25% of mutations drop out.

**Comment by quaidmorris** [comment]
Hi @callosciurus

The four variants that the parser filters out lie outside of the ranges for ch16 and ch17 specified in your input CN file. As we indicate in the instructions, if your variant lies outside the range, we assume that the CN for that region cannot be called (due, e.g., to bad data?) and we filter out the variants. If you want them included, you need to explicitly indicate that the CN in those regions are normal.
