### ISSUE TITLE
inferring subclonality - cluster assignment?

### ISSUE THREAD

**Issue by bryanlouie** [morrislab/phylowgs#34]
Hi,
I've been testing PhyloWGS on a number or mock data sets to see how it responds and I have a question about how the ssms are clustered into different populations.  Specifically, I've been experimenting with a data set as follows:

id   gene  a         d          mu_r   mu_v
s0   a     500,500   1000,1000  0.999  0.5
s1   b     500,500   1000,1000  0.999  0.5
s2   f     750,500   1000,1000  0.999  0.5
s3   g     750,500   1000,1000  0.999  0.5
s4  k     750,1000  1000,1000  0.999  0.5
s5  l     750,1000  1000,1000  0.999  0.5
s6  p     1000,500  1000,1000  0.999  0.5
s7  q     1000,500  1000,1000  0.999  0.5
s8  u     1000,750  1000,1000  0.999  0.5
s9  v     1000,750  1000,1000  0.999  0.5
(the two samples are assumed to be initial and recurrent tumor samples)

The rationale behind this data is that mutations with a = 500 are clonal, a = 750 are subclonal, and a = 1000 are absent. Overall, the result that I get is almost consistent with this, however, one thing I noticed is that PhyloWGS groups s0,s1 with s2,s3 and infers 1 clonal cancerous population.  I was curious how this happens, because s2 and s3 have an implied pop. freq. of ~50% in sample 1 and therefore I assumed they would be considered subclonal and differentiated from the clonal population (s0/s1).  I did try making the subclonal group with a = 900 (freq = 20%) and found that the program did differentiate between the the two groups.  
 
So, I'm wondering why mutations s2/s3 with pop. freq. of 50% are not grouped on their own.  If you could provide any rationale on why this is the case that would be greatly appreciated.  

Thank you!

**Comment by quaidmorris** [comment]
Hi @bryanlouie 

Thanks for your question!

Have you tried rerunning PhyloWGS a number of times, starting with different random seeds, to see whether PhyloWGS consistently avoids your intended solution?

Assuming that you have, then I suspect this is happening because PhyloWGS strongly prefers solutions where there is some flexibility in the pop freqs (pfs) of the clonal and subclonal populations. In your example, these pfs are highly constrained in the tree that you intend. Specifically, the pf of s2/s3 + the pf of s4/s5 has to be less than that of the s0/s1 population. With a=900, there is much more flexibility in these pfs in your intended tree, so it is more favoured by PhyloWGS.

The reason for this preference is that we are using Bayesian inference to score trees, so trees which permit more variability in the pfs are preferred over those that do not. I am somewhat surprised that the preference would be so strong to overcome the large difference in datafit between your intended tree and the one that PhyloWGS prefers. One thing that you could try is to scale up the a,d values to put more emphasis on datafit to see whether that makes any difference. You could also titrate the a=900 value, to see where PhyloWGS switches its preferences.

Thank-you for trying out PhyloWGS and bringing this case to our attention!

**Comment by quaidmorris** [comment]
Hi @bryanlouie,
We haven't heard from you in a week or so; I will close this issue soon.
