### ISSUE TITLE
Question: CNVs from JSON Results

### ISSUE THREAD

**Issue by ShadrielleE** [morrislab/phylowgs#37]
Hello,

After running the workflow you've described, it generates JSON files for each tree generated, and from these JSON files, we can extract the SSMs assigned to each node (and what those SSMs are). Although the JSON files also output list of CNVs assigned to each node by id (c0, c1, c2, etc.), there is no obvious way to map these CNVs back to cnvs.txt.

After looking through the source code, it seems that your parser merges all clonal CNVs as "c0", but how about the others?

Thanks
Shadrielle

**Comment by quaidmorris** [comment]
Hi @ShadrielleE,

@jwintersinger is working on this right now.

**Comment by jwintersinger** [comment]
Hi Shadrielle,

I've added this functionality. We now distinguish between "physical" and "logical" CNVs.

* Physical CNVs have attributes like start position, end position, chromosome, major & minor allele, and cellular prevalence. They appears in `cnvs.txt`.

* Logical CNVs are the `c0`, `c1`, ... events appear in `cnv_data.txt`. They have only the attributes `a`, `d`, and the list of SSMs affected by the CNV.

The correspondence between logical and physical CNVs is not straightforward. All the clonal physical CNVs will be merged into a single logical CNV, so that they will move around the sampled trees as a single entity; in multisample data, a single physical CNV may be split into multiple logical CNVs, so that we can define genome regions with the same major and minor allele across samples that have different CNV breakpoints.

Ideally, as a PhyloWGS user, you won't ever have to worry about logical CNVs -- you'll encounter only physical CNVs when generating the inputs, and see only physical CNVs when examining the outputs. We're not yet there, but we'll eventually reach that point.

To see how your physical CNVs have been assigned to your trees, you'll need to repeat the full workflow: generate your inputs via `parser/create_phylowgs_inputs.py`, run via `evolve.py`, and generate JSON outputs via `write_results.py`. Once you do, your `mutlist` output (e.g., `muts.json.gz`) will include information on the physical CNVs:

```
$ gunzip < muts.json.gz | jq . | head -n25
{
  "dataset_name": "example",
  "cnvs": {
    "c0": {
      "physical_cnvs": [
        {
          "end": 5678,
          "start": 1234,
          "major_cn": 2,
          "cell_prev": [
            0.8
          ],
          "chrom": "1",
          "minor_cn": 1
        },
        {
          "end": 10000,
          "start": 15,
          "major_cn": 2,
          "cell_prev": [
            0.8
          ],
          "chrom": "X",
          "minor_cn": 0
        },
```

Please let me know if you have any questions!
