### ISSUE TITLE
PhyloWGS Threading and runtime

### ISSUE THREAD

**Issue by mjz1** [morrislab/phylowgs#38]
Just wondering if PhylsoWGS can work with multiple CPUs, and the expected runtime.

I'm dealing with hypermutated cancer genomes with 1 million+ mutations.

**Comment by quaidmorris** [comment]
Hi @mjz1,
Thanks for your question!

In our experience, the number of clusters depends largely on the read depth and ploidy of the sample rather than the number of mutations. So, using a random subset of the mutation (say 10k) should give you similar results in terms of clusters and phylogeny. This is single thread right now, but for you it might make sense to run PhyloWGS multiple times with different subsets and check the answers against one another.

However, if you want to assign your 10^6 mutations to the clusters, we have some code for doing post hoc assignment to the nodes and phylogenies after an initial run of PhyloWGS. This can run on multiple CPUs. @jwintersinger is this code in the main branch?

Also, since you have so many mutations, you might consider contacting us to use PhyloSpan which gives improved phylogenies when multiple mutations are covered by the same read.

**Comment by mjz1** [comment]
Subsumpling with post hoc assignment, as well as using this PhyloSpan tool would definitely be important for this project. We were hoping to assign each mutation to a node.

**Comment by quaidmorris** [comment]
@mjz1,
We have posthoc assignment, but it's not in the main branch. Check out the posthocassignment branch. We're not really in a position to support that right now but will try to add it when we have more time.
