### ISSUE TITLE
About the CNV input

### ISSUE THREAD

**Issue by Chuan-Jiang** [morrislab/phylowgs#57]
Hi, Quaid Morris,

As i need to to prepare the CNV input file from facets, I have to write my own script. 
But, I don't quite understand the meaning of column "a" and "d".
CNV is one genome region, How should I count the number of reference-allele reads and total reads?
Does the reference-allele reads means all reads covering one specific SNV locus but without mutation? But these numbers have already exist in file ssm_data.txt. 

Thank you very much!

**Comment by quaidmorris** [comment]
Hi Chuan-Jiang,
In order for PhyloWGS to cluster CNAs (what we now call CNVs) with SNVs, we need some estimate of their cellular prevalence (CP) and our confidence level in that estimate. CP is the proportion of cells in the sample with the CNA, so if the CNA is clonal then its CP is the purity of the sample; if it is subclonal, then its CP is smaller. The "a" and "d" columns provide a way to communicate CP and confidence to PhyloWGS.

The "d" value is a measure of confidence, and the "a" value is used to communicate the CP.

You should set: `a = d*(1-CP/2)`

And for `d`, right now we use the following heuristic:

`d = RD*min(3000, 7*length_of_CNA / (10^4))`

Where `RD` is the average read depth, and `length_of_CNA` is the number of bases in the CNA.

Essentially what this heuristic does is set confidence in terms of equivalent number of SNVs. Our confidence in an individual SNV's CP is determined by the read depth at the locus. So the term,

`min(3000,7*length_of_CNA / (10^4))`

is the equivalent number of SNVs. This term says that the equivalent number is 7 SNVs per 10kb of CNA, with a maximum of 3000. We use this heuristic because CNAs are generally called using heterozygous SNPs, and there are about 7 heterozygous SNPs per 10kb.

**Comment by Chuan-Jiang** [comment]
Thank you Dr. Morris.
