### ISSUE TITLE
How to derive clonal CNVs?

### ISSUE THREAD

**Issue by pankevich-ev** [morrislab/phylowgs#73]
Hi,

is there an easy way to derive clonal CNVs from PhyloWGS output? It would be great to obtain an assignment of each CNA to different clones. Does PhyloWGS actually allow this?
I'm looking for a solution such as the one described for clonal mutations in #48. 

Thanks in advance and all the best!

**Comment by jwintersinger** [comment]
For each CNA you provide as input, we create an associated pseudo-SSM to be placed in the tree. Clonal CNAs work somewhat differently, however. For clonal CNAs, which we identify as CNAs whose cellular prevalence reaches the maximum seen across all provided CNAs, we merge them into a single event so that they will all be placed into the same population in the tree. This single event should correspond to the CNA `c0`.

So, to determine where your clonal CNAs are in the tree, you must find which population has the `c0` event. You can do this by examining the `mutass.zip` file generated by `write_results.py`, which will show you the mutation assignments in each sampled tree. To start with, I suggest looking at whichever tree is identified as the "best" tree in the scatterplot shown under the "Tree summaries" tab.

Please let me know if we can offer any other help!
